version: '3'
services:
  client:
    image: cytlin/ip2-client-side-image:v1.0.0
    ports:
      - 3000:3000
    command: npm start

  backend:
    image: cytlin/ip2-backend-side-image:v1.0.0
    ports:
      - 5000:5000
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb//mongo/yolodatabase

  mongo:
    image: mongo:latest
    command: mongod --bind_ip_all
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
