version: '3'
services:
  client:
    image: client-side-image:1.0.0
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - 3000:3000

  backend:
    image: backend-side-image:1.0.0
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb//mongo/yolodatabase

  mongo:
    image: mongo:latest
    command: mongod --bind_ip_all
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
