---
- name: Manage Ubuntu Server
  hosts: all
  become: yes

  roles:
    - role: initial-set-up
      tags: setup

    - role: docker-set-up
      tags: setup

    - role: client
      tags: front-end-setup

    - role: backend
      tags: backend-setup

    - role: mongodb
      tags: db-setup
