- include_vars: ../../common_vars/main.yml

- name: Pull Backend Docker image from Docker Hub
  shell: docker pull {{ backend_image }}

- name: Run Backend Container with MongoDB Link
  shell: docker run -d --name backend_container -p {{ backend_port_number }}:{{ backend_port_number }} --link mongo_container:mongo -e MONGODB_URI=mongodb://mongo/yolodatabase {{ backend_image }}
