- name: Pull Client Docker image from Docker Hub
  shell: docker pull cytlin/ip2-client-side-image:v1.0.0

- name: Run Client Container
  shell: docker run -d --name client_container -p 3000:3000 cytlin/ip2-client-side-image:v1.0.0
