- include_vars: ../../common_vars/main.yml

- name: Pull Client Docker image from Docker Hub
  shell: docker pull {{ client_image }}

- name: Run Client Container
  shell: docker run -d --name client_container -p {{client_port_number}}:{{client_port_number}} {{ client_image }}
